language: node_js
node_js:
  - "4.1"
sudo: required
before_install:
  - sudo apt-get update
  #- wine
  - sudo apt-get install -qq -y wine winetricks
  - sudo apt-get install wine-mono4.5.6\*
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - export WINEARCH=win32
  - export WINEPREFIX=~/.wine32
  - env WINEARCH=win32 WINEPREFIX=~/.wine32 winetricks -q dotnet20
  #- env WINEARCH=win32 WINEPREFIX=~/.wine32 winetricks -q mono28
  #- mkdir -p $HOME/.wine/drive_c/windows
  #- chmod -R 775 $HOME/.wine
  #- rm -rf $HOME/.wine
  #- WINEARCH=win32 winecfg
  #- winetricks -q dotnet20
  #- winetricks -q mono28
  #-
  - npm install -g bower
  - npm install -g nw-builder
  - mkdir -p cache/0.12.3 && mkdir builds
  - cd cache/0.12.3
  - wget http://dl.nwjs.io/v0.12.3/nwjs-v0.12.3-linux-x64.tar.gz
  - wget http://dl.nwjs.io/v0.12.3/nwjs-v0.12.3-win-x64.zip
  - tar xzf nwjs-v0.12.3-linux-x64.tar.gz && rm nwjs-v0.12.3-linux-x64.tar.gz
  - unzip nwjs-v0.12.3-win-x64.zip && rm nwjs-v0.12.3-win-x64.zip
  - mv nwjs-v0.12.3-linux-x64 linux64
  - mv nwjs-v0.12.3-win-x64 win64
  - cd ../..
  - cp codecs-libs/libffmpegsumo.so cache/0.12.3/linux64
  - cp codecs-libs/ffmpegsumo.dll cache/0.12.3/win64
install:
  - cd src
  - npm install
  - bower install
  - cd ..
script:
  - ls -l
  - ls -l cache
  - ls -l cache/0.12.3
  - ls -l cache/0.12.3/linux64
  - nwbuild -p linux64 -v 0.12.3 --cacheDir ./cache --buildDir ./builds                     ./src | grep -v ^Zipping #quiet
  - env WINEARCH=win32 WINEPREFIX=~/.wine32 nwbuild -p win64   -v 0.12.3 --cacheDir ./cache --buildDir ./builds --winIco ./icon.png ./src | grep -v ^Zipping #quiet